version: "3"

services:
  web:
    image: "drydockcloud/drupal-acquia-httpd:${TAG:-latest}"
    volumes:
      - .:/var/www
    depends_on:
      - php
  php:
    image: "drydockcloud/drupal-acquia-php-${VERSION:-7.3}:${TAG:-latest}"
    volumes:
      - .:/var/www
    depends_on:
      - mysql
  mysql:
    image: "drydockcloud/drupal-acquia-mysql:${TAG:-latest}"
